version: 2.1
jobs:
    build:
        docker:
            - image: ubuntu:21.10 # the primary container, where your job's commands are run
        steps:
            - checkout # check out the code in the project directory
            - run:
                  name: Install clang, make, libkqueue, nodejs, npm # nodejs & npm are needed for integration tests
                  command: |
                      apt update && DEBIAN_FRONTEND='noninteractive' apt install -y clang make libkqueue-dev nodejs npm
            - run:
                  name: Install dependencies
                  command: npm install
            - run:
                  name: Build webserver
                  command: make
            - run:
                  name: Run webserver & integration tests in parallel
                  command: npm run start
            - store_artifacts:
                  path: ~/project/artifacts
