version: 2.1
jobs:
    build:
        working_directory: ~/webserv_project
        docker:
            - image: ubuntu:21.10 # the primary container, where your job's commands are run
        steps:
            - checkout # check out the code in the project directory
            - run:
                  name: Install clang, make, libkqueue, python3-pip # the last is needed for the integration tests
                  command: |
                      apt update && DEBIAN_FRONTEND='noninteractive' apt install -y clang make libkqueue-dev git python3-pip
            - run:
                  name: Reset git (workaround for CircleCI bug)
                  command: git reset --hard
            - run:
                  name: Install dependencies
                  command: pip install -r requirements.txt
            - run:
                  name: Build webserver
                  command: make
            - run:
                  name: Run unit tests
                  command: cd tests/unit_tests && make && ./unit_tests
            - run:
                  name: Run integration tests
                  command: ./run_integration_tests.sh
