version: 2.1
jobs:
    build:
        docker:
            - image: debian:buster # the primary container, where your job's commands are run
        steps:
            - checkout # check out the code in the project directory
            - run:
                  name: Install clang # Update List of packages and install clang
                  command: |
                      apt-get update && apt-get install -y clang
            - run:
                  name: Build Unit Tests
                  command: |
                      cd tests && clang++ main_test.cpp -fsanitize=address  -std=c++11 -o unit_tests && ./unit_tests
